cache: 
  directories: "-node_modules"
deploy: 
  cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  provider: pages
  true: 
    branch: main
language: node_js
node_js: "7.4.0"
script: "-npm run fix -npm test -npm run build"

