cache: 
  directories: "-node_modules"
deploy: 
  github_token: $GITHUB_TOKEN
  local_dir: build
  provider: pages
  skip_cleanup: true
  true: 
    branch: main
language: node_js
node_js: "-\"stable\""
script: "-npm run fix -npm test -npm run build"
