cache: npm
deploy: 
  cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  provider: pages
  true: 
    branch: main
jobs:
  include:
    - language: node_js
      name: test
      install: cd django_react_proj/users-fe/ && npm install
      script: npm test
      stage: test
    - language: node_js
      name: build
      install: cd django_react_proj/users-fe/ && npm install
      script: npm run build
      stage: build
    - language: node_js
      name: fix
      install: cd django_react_proj/users-fe/ && npm install
      script: npm run fix
      stage: fix
language: node_js
node_js:
  - 15
stages: 
  - build 
  - test 
  - fix


