deploy: 
  api_key: 
    secure: 2b6009bc-775a-4650-8ff9-248ac6baafe9
  app: Daily-Planner
  provider: heroku
jobs: 
  include: 
    - 
      cache: 
        directories: 
          - ./django_react_proj/users-fe/node_modules
      install: "cd django_react_proj/users-fe/ && npm install"
      language: node_js
      name: test
      script: "npm test"
      stage: test
    - 
      cache: 
        directories: 
          - ./django_react_proj/users-fe/node_modules
        npm: true
      install: "cd django_react_proj/users-fe/ && npm install"
      language: node_js
      name: build
      script: "npm run build"
      stage: build
    - 
      cache: 
        directories: 
          - ./django_react_proj/users-fe/node_modules
        npm: true
      install: "cd django_react_proj/users-fe/ && npm install"
      language: node_js
      name: fix
      script: "npm run fix"
      stage: fix
    - 
      cache: 
        directories: 
          - ./django_react_proj/users-fe/node_modules
        npm: true
      install: "cd django_react_proj/users-fe/ && npm install"
      language: node_js
      name: eslint
      script: "npm run eslint"
      stage: eslint
    - 
      before_script: 
        - "cd django_react_proj"
      install: "pip install -r requirements.txt"
      language: python
      name: backend
      script: 
        - "python manage.py test"
      stage: backend
language: node_js
node_js: 
  - 15
python: 
  - 3.8
stages: 
  - build
  - test
  - eslint
  - fix
