cache: npm
deploy: 
  cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  provider: pages
  true: 
    branch: main
include: 
  - 
    name: test
    script: npm test
    stage: test
  - 
    name: build
    script: npm run build
    stage: build
  - 
    name: eslint
    script: npm run eslint
    stage: eslint
  - 
    name: fix
    script: npm run fix
    stage: fix
jobs: ~
language: node_js
node_js: "7.4.0"
stages: 
  - build 
  - test 
  - eslint 
  - fix


