# Generated by Django 3.2 on 2021-06-01 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user_taskpriority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=254, verbose_name='Email'),
        ),
    ]
