# Generated by Django 3.2 on 2021-05-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210511_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='taskPriority',
            field=models.IntegerField(default=1, verbose_name='TaskPriority'),
        ),
    ]
