# Generated by Django 3.2 on 2021-04-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_user_tasktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='taskType',
            field=models.CharField(default='Meeting', max_length=100, verbose_name='Done'),
        ),
    ]
