# Generated by Django 3.2 on 2021-05-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_tasktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='taskDescription',
            field=models.CharField(default='', max_length=500, verbose_name='TaskDescription'),
        ),
        migrations.AddField(
            model_name='user',
            name='taskName',
            field=models.CharField(default='', max_length=100, verbose_name='TaskName'),
        ),
    ]
